### ISSUE TITLE
Line number is not shown on MSBuild task error

### ISSUE THREAD

**Issue by uhaciogullari** [PureKrome/YUICompressor.NET#7]
I guess YUI Compressor can show the error line and column. [An online compressor](http://refresh-sf.com/) was able to find the location of the error. However MSBuild task doesn't show any details.

![yui](https://cloud.githubusercontent.com/assets/1431130/7928855/162b507a-08ff-11e5-9fff-14463e231f02.png)

**Comment by freeranger** [comment]
Hi,

This is not an issue with the msbuild task - there is currently no way to provide line number information regardless of how you call the compressor.
Our implementation of YUI compressor relies on a separate ECMAScript parser to read and parse the JavaScript files.  It does not currently support line numbers.
You should raise the issue here: https://github.com/PureKrome/EcmaScript.NET and once it is implemented there, it will flow through to us.
The online compressor you tried is using the Java YUI compressor, rather than our .NET port.

Closing because there's nothing we can do here.
