### ISSUE TITLE
Unable to individually minify all .js files in folder+subfolders

### ISSUE THREAD

**Issue by Golfenstein3D** [PureKrome/YUICompressor.NET#8]
Based on the CSS example in MsBuildSample.xml I expected this to overwrite each .js file with the minified version without changing the filename, but I get "error : Output file cannot be the same as source file(s)."  All the examples I've found for v2.7.0 involve concatenating files, but I'm trying to update YUI compressor for an existing site that does not concatenate files.

    <ItemGroup>
      <JSFiles Include="$(PublishRoot)\assets\js\**\*.js" />
    </ItemGroup>
    <JavaScriptCompressorTask
        SourceFiles="@(JSFiles)"
        OutputFile="%(JSFiles.Identity)"
    />
    

I will concatenate some files, but it's a large site with so many files (and so many pages pointing to those files), that the individually-minified files will need to remain on the servers for quite a while.

**Comment by freeranger** [comment]
Hi,

It is not possible to override the files you are compressing.  If you think about it, this doesn't make any sense.  What happens when you want to edit them after compression? They are now minified so you're going to find it a bit tricky.  And they are already minified so you will be trying to minified minified files.
And you are trying to minify the very files you are currently reading.  Now this implementation does not use streams but a future implementation might...so how do you read from a stream and write to an earlier part of it at the same time?

There are a couple of ways to achieve what you want:
- move the .js files to a src directory and minify them to the location you want to run them from
- if you really, really want to overwrite the originals then minify them as .min.js or something like that and then a separate msbuild step renames them as .js

The only time them latter makes sense to me is if you are minifying once you have deployed so when you want to edit the files, you go back to your project source.
Typically, I minify at compile time so the former option would be then one I choose.

**Comment by Golfenstein3D** [comment]
Well, at least it made sense to whoever wrote the old version of this library.  If you think about files being minified on a build server, where they will never be edited, the extra step of copying files to/from a separate folder doesn't make much sense.

(What I really, really want to do is switch from msbuild to grunt or gulp, but... not enough time now.)

**Comment by freeranger** [comment]
Sorry, not getting you about it making sense to whoever made the old version of the library - why do you say that?  I don't believe there was ever an intention to allow you to overwrite the file you are reading - but perhaps @PureKrome can correct me on that since he is the original author.

You can achieve the desired effect as I said with additional MSBuild steps anyway.

We run the same build locally as on the build server so replacing the original file would not make sense in that scenario

re: grunt/gulp - gulp is gaining a lot of traction these days and will come with first class support in VS2015 so I would suggest going that route if you are moving.
grunt has been around longer and there are more modules available for it, but that is changing and I think gulp will eventually overtake grunt as the tool of choice.

Note though that gulp is stream based so definitely won't support what you want to do in a single step either....

**Comment by PureKrome** [comment]
Heya @Golfenstein3D.

Ok - I'll talk about the rational (at the time) about what I did. The idea was that you _never_ touch your source. It's _the source_ after all. @freeranger got it right (above). Once you've messed with the source, you can't go back and undo that.

How does this impact with your project? Glad you asked! The idea is that you create a _copy_ of the source .. into another file .. and this copy is the _modified_ result. Modified (in this case) is the minified version of the source.

Don't forget that this project has been around for _ages_ (in internets time). Before we had gulp/grunt/<waaaaaaay better tools> and better tech. Back then, the general idea was to have 

1. `someFile.js` <-- source
2. `someFile.min.js`  <-- transformed result

(Tip: check out what jQuery does for their naming....)

so I just followed that pattern at the time.

Secondly, it was also a _safety-play_. Meaning, I didn't want people to start out by running YUIC and they modified their source accidentally because they failed to read the FAQ, etc (seriously, who _really_ reads instructions 100% the first time they try something .. besides you and a few of your mates?) So by adding in that safety trigger, I was hoping to protect those peeps (read: me) who accidentally forget to set some target file name or whatever. Ok - I was protecting myself .. there I said it. 

Last reason was also to promote the use of _file combing_. Making the developer think about not just mining, but combining the results into one out-file file -- reduce the number of requests to the server, blah blah blah...

So those are/were the reasons.

**Comment by freeranger** [comment]
Thanks for filling in the blanks @PureKrome - those reasons aside though, as I said, if we moved to streaming (or @Golfenstein3D moved to gulp, which is streaming) then you can't overwrite the files you are reading anyway.

The title of this issue does not match the description either - you CAN minimise files individually using standard msbuild/nant functionality to pass a file at a time to a task - we have given examples of this elsewhere previously.

Given that, and workarounds have been described to the issue in the description (not the title!), I am closing the issue as there is no issue to be worked on.
